In [1]:
#Import all the necessary packages 
import cv2
import numpy as np 
import glob 
from sklearn import svm 
from sklearn.externals import joblib
from sklearn import model_selection

In [2]:
#all constant values
folder_depth = 8 
image_x = []
image_y = []
files = []
image_location = "/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/"


In [3]:
#Read a single from image and to add in numpy array
image_location = "/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.png"
i_mg = cv2.imread(image_location,0)
print(i_mg.flatten().tolist())
new_x = []
new_x.append(i_mg.flatten().tolist())
print("new_x",new_x)
print("np array ", np.array(new_x))


[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 250, 249, 252, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 49, 0, 0, 0, 0, 0, 0, 0, 0, 5, 255, 255, 255, 255, 255, 255, 255, 255, 255, 195, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 59, 0, 0, 0, 5, 103, 103, 103, 103, 103, 0, 0, 0, 0, 0, 152, 255, 255, 255, 255, 171, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 100, 255, 255, 255, 255, 255, 255, 255, 255, 24, 24, 5, 0, 0, 0, 0, 21, 231, 0, 0, 0, 99, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,

In [4]:
x_image = i_mg
print(x_image)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [5]:
#To get all the images in the images folder 
for level in range(folder_depth):
    folder = chr(ord("a")+level)
    print (image_location+folder+"/")
    label_len = len(glob.glob(image_location+folder+"/"+"*.png"))
    files = files + glob.glob(image_location+folder+"/"+"*.png")
    print(files)
    image_y = image_y + [folder] * (label_len)



/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pnga/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngb/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngc/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngd/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pnge/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngf/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngg/
[]
/home/syedjafer/Documents/Handwriting_recognition_svm/test1/images/a/a_01.pngh/
[]


In [6]:
print (x_image)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [7]:
print (image_x)

[]


In [8]:
print (image_y)

[]


In [11]:
# adding dataset images to numpy array
for file in files:
    
    image = cv2.imread(file)
    image_x.append(image.flatten().tolist())
    print(image)
    print(image_x)
print (image_x)
print (" image_x ",np.array(image_x),np.array(image_x).shape)

[]
 image_x  [] (0,)
