In [3]:
#imports
import cv2
import os
import random
import matplotlib.pylab as plt
import glob
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [32]:
# knowing shapes of my image
files = glob.glob("*.png")
for file in files:
    image = cv2.imread(file)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     print ("shape of image ",gray.shape)
    resized_image = cv2.resize(image, (100, 100))
    filename = file
    cv2.imwrite(file, resized_image)
    
    

In [7]:
ls


 a_00.png   a_07.png   a_14.png   a_21.png
 a_01.png   a_08.png   a_15.png  'images to numpy arrays .ipynb'
 a_02.png   a_09.png   a_16.png   svm_handwriting.ipynb
 a_03.png   a_10.png   a_17.png   Untitled.ipynb
 a_04.png   a_11.png   a_18.png   x_images_arrays.npz
 a_05.png   a_12.png   a_19.png   y_infiltration_labels.npz
 a_06.png   a_13.png   a_20.png


In [8]:
files = glob.glob("*.png")
for file in files:
    image = cv2.imread(file)
    print ("shape ", image.shape)

shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)
shape  (200, 200, 3)


In [12]:
train_files = []
y_train = []
i=0
for _file in files:
    train_files.append(_file)
    y_train.append("a")
print("Files in train_files: %d" % len(train_files))


Files in train_files: 22


In [15]:


from scipy import ndimage
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img


image_width = 200
image_height = 200
ratio = 4

image_width = int(image_width / ratio)
image_height = int(image_height / ratio)

channels = 3
nb_classes = 1

i = 0
for _file in train_files:
    img = load_img(_file)  # this is a PIL image
    img.thumbnail((image_width, image_height))
    # Convert to Numpy Array
    x = img_to_array(img)  
    

In [33]:
new_x = []
new_y = []
files = glob.glob("*.png")
for file in files:
    image = cv2.imread(file)
    new_x.append(image)
    new_y.append("a")

    

In [34]:
print (new_x)
print (new_y)

[array([[[232, 232, 232],
        [232, 232, 232],
        [232, 232, 232],
        ...,
        [230, 230, 230],
        [230, 230, 230],
        [231, 231, 231]],

       [[232, 232, 232],
        [232, 232, 232],
        [232, 232, 232],
        ...,
        [233, 233, 233],
        [233, 233, 233],
        [234, 234, 234]],

       [[232, 232, 232],
        [232, 232, 232],
        [231, 231, 231],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [232, 232, 232]],

       ...,

       [[230, 230, 230],
        [230, 230, 230],
        [231, 231, 231],
        ...,
        [230, 230, 230],
        [231, 231, 231],
        [232, 232, 232]],

       [[230, 230, 230],
        [230, 230, 230],
        [230, 230, 230],
        ...,
        [230, 230, 230],
        [231, 231, 231],
        [231, 231, 231]],

       [[229, 229, 229],
        [229, 229, 229],
        [229, 229, 229],
        ...,
        [231, 231, 231],
        [230, 230, 230],
        [229, 229, 229]

In [36]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100)
clf.fit(new_x,new_y)



ValueError: Found array with dim 4. Estimator expected <= 2.

In [46]:
_x = np.array(new_x)
print (_x.shape)
_x.reshape(())

(22, 100, 100, 3)


In [35]:
print (np.array(new_x))

[[[[232 232 232]
   [232 232 232]
   [232 232 232]
   ...
   [230 230 230]
   [230 230 230]
   [231 231 231]]

  [[232 232 232]
   [232 232 232]
   [232 232 232]
   ...
   [233 233 233]
   [233 233 233]
   [234 234 234]]

  [[232 232 232]
   [232 232 232]
   [231 231 231]
   ...
   [231 231 231]
   [231 231 231]
   [232 232 232]]

  ...

  [[230 230 230]
   [230 230 230]
   [231 231 231]
   ...
   [230 230 230]
   [231 231 231]
   [232 232 232]]

  [[230 230 230]
   [230 230 230]
   [230 230 230]
   ...
   [230 230 230]
   [231 231 231]
   [231 231 231]]

  [[229 229 229]
   [229 229 229]
   [229 229 229]
   ...
   [231 231 231]
   [230 230 230]
   [229 229 229]]]


 [[[228 228 228]
   [229 229 229]
   [230 230 230]
   ...
   [230 230 230]
   [230 230 230]
   [229 229 229]]

  [[229 229 229]
   [227 227 227]
   [227 227 227]
   ...
   [232 232 232]
   [232 232 232]
   [231 231 231]]

  [[230 230 230]
   [229 229 229]
   [229 229 229]
   ...
   [230 230 230]
   [230 230 230]
   [231 231

In [21]:
print (gray.shape)

(50, 50)


In [49]:
print (gray)
print (x.reshape(75,100))
clf.fit(x,y_train)


[[232 232 232 ... 230 230 231]
 [232 232 232 ... 231 231 231]
 [232 232 232 ... 233 233 233]
 ...
 [228 228 228 ... 231 231 230]
 [228 228 228 ... 230 229 228]
 [230 230 230 ... 230 229 228]]
[[228. 228. 228. ... 233. 233. 231.]
 [231. 231. 232. ... 232. 232. 232.]
 [232. 230. 230. ... 229. 229. 229.]
 ...
 [230. 230. 230. ... 228. 228. 227.]
 [227. 227. 229. ... 230. 229. 229.]
 [229. 230. 230. ... 230. 230. 230.]]


ValueError: Found array with dim 3. Estimator expected <= 2.

In [1]:
files

NameError: name 'files' is not defined